apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-streamlit
  labels:
    app: portfolio-streamlit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-streamlit
  template:
    metadata:
      labels:
        app: portfolio-streamlit
    spec:
      containers:
      - name: portfolio-streamlit
        image: portfolio-streamlit:latest
        ports:
        - containerPort: 8501
        env:
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5 